### ISSUE TITLE
Exclude javascript files from being formatted, with options auto_save = true

### ISSUE THREAD

**Issue by jorgeaguirre** [rosshemsley/SublimeClangFormat#13]
I don't want to format `.js` files with SublimeClangFormat, only `.cpp` files. Is there any way to exclude files types from being formatted?

**Comment by gelraen** [comment]
+1, spent half an hour figuring out WTF is going on here. Maybe a better option would be to expose the list of languages in the settings file.

**Comment by sailorswift** [comment]
In your user settings, you can now list what languages you want ClangFormat to run on.  Just remove JavaScript from the default languages and you're good to go!

**Comment by gelraen** [comment]
Thanks! \o/
