### ISSUE TITLE
Please update all_settings in clang_format.py for clang format 3.7

### ISSUE THREAD

**Issue by jasjuang** [rosshemsley/SublimeClangFormat#18]
There is a important new feature I would like to have that is only available in clang format 3.7, which is "AlignConsecutiveAssignments". I am able to run clang format 3.7 with this feature on command line. After sometime of digging into why passing this argument has no effect on sublime, I came to the conclusion that It looks like the fix is to add the new settings in all_settings in clang_format.py. Please update. Thank you!

**Comment by rosshemsley** [comment]
Ah great, to hear they have added this! I will try and get around do it. Pull Requests gladly accepted ;) :)

**Comment by jasjuang** [comment]
I would love to do it if I know Python, but unfortunately I don't. I am not sure if it's just simply adding "AlignConsecutiveAssignments" into all_settings. Hope you can update it soon so we can all enjoy it :)

**Comment by sailorswift** [comment]
It is as simple as that! :smile: 

If you know of any other new features included in clang-format 3.7, I can add them all in one commit and send a Pull Request.

**Comment by jasjuang** [comment]
@sailorswift it's here for 3.7 http://clang.llvm.org/docs/ClangFormatStyleOptions.html

**Comment by jasjuang** [comment]
The new features are (hopefully I didn't miss anything)

AlignAfterOpenBracket
AlignConsecutiveAssignments
AlignOperands
AllowShortBlocksOnASingleLine
AllowShortCaseLabelsOnASingleLine
AlwaysBreakAfterDefinitionReturnType
BinPackArguments
DerivePointerAlignment
DisableFormat
ForEachMacros
MacroBlockBegin
MacroBlockEnd
ObjCBlockIndentWidth
PointerAlignment
SpaceAfterCStyleCast
SpacesInSquareBrackets

**Comment by sailorswift** [comment]
If you need these features immediately, feel free to pull from https://github.com/sailorswift/SublimeClangFormat which has my 3 pull requests merged in.  @rosshemsley seems pretty active and I'll fix any issues with the requests immediately so you probably won't be waiting that long. :smiley:

**Comment by jasjuang** [comment]
@sailorswift Your fork works phenomenally! Thanks a lot!
