### ISSUE TITLE
encoding issues?

### ISSUE THREAD

**Issue by adrianN** [rosshemsley/SublimeClangFormat#23]
Hi,

I found a problem in the llvm plugin that I think might also happen in your version. I don't have ST3 so I can't check. It would be cool if you could join the discussion on the cfe-dev mailinglist.

See here:

http://lists.llvm.org/pipermail/cfe-dev/2015-August/044561.html

**Comment by adrianN** [comment]
I installed Sublime Text 3 and your plugin and confirmed that you also have these encoding issues.

     File "clang_format in C:\Users\z003fuea\AppData\Roaming\Sublime Text 3\Installed Packages\Clang Format.sublime-package", line 224, in run
    LookupError: unknown encoding: Western (Windows 1252)

**Comment by rosshemsley** [comment]
Hey!

I'm aware of these issues but my real job is unfortunately getting in the way of looking after these side projects right now.

However, I'm happy to accept collaborators wishing to help fix and improve! :)

**Comment by adrianN** [comment]
I submitted a pull request that fixes the problem for me. It might not be the prettiest solution, because I don't know the Sublime Text API.

**Comment by rosshemsley** [comment]
The API docs are quite good. Though a little incomplete. I found googling around for similar plugins the best way to figure stuff out.

Feel free to add fix when you are happy!

**Comment by adrianN** [comment]
So I checked the API docs and didn't find a nicer way of getting the right encoding string. I guess the way I do it in the pull request will have to be good enough. Please have a look at my pull request and merge it if you think that it's ok.
