### ISSUE TITLE
Please update all_settings in clang_format.py for clang format 3.8

### ISSUE THREAD

**Issue by jasjuang** [rosshemsley/SublimeClangFormat#26]
There is an important new feature I would like to have that is only available in clang format 3.8, which is "AlignOperands". I am able to run clang format 3.8 with this feature on command line. Please update. Thank you!

I opened a pull request a week ago but got no response. Please look into it.

**Comment by adrianN** [comment]
If I did everything right, we should now have a new released with your pull request merged in.
