### ISSUE TITLE
Keybindings don't work under Linux and Windows

### ISSUE THREAD

**Issue by pradyunsg** [rosshemsley/SublimeClangFormat#27]
In linux and window, the option key is referred to as the alt key. This means that the keybindings do not work on Linux and Windows.

Solution: Change the option in Keybinding (Windows & Linux) to say alt instead of option.

**Comment by PeterFeicht** [comment]
The key bindings work fine for me on Linux. Although I was wondering about the `option` thing myself...

**Comment by pradyunsg** [comment]
I switched editors. I don't really care about this now.
