### ISSUE TITLE
I Found "SortIncludes" is not worked

### ISSUE THREAD

**Issue by wikinee** [rosshemsley/SublimeClangFormat#39]
I do not want SortIncludes my #include files, so I add setting 
{
    ...
   "SortIncludes": false
    ...
}
is not worked.
My Config is sublime-text-3, clang-format 3.8

**Comment by sailormoon** [comment]
Use `"IncludeCategories": "UINT_MAX"`.

**Comment by wikinee** [comment]
It's will give a warning says: not sequence... I' m on the Ubuntu 16.04

**Comment by wikinee** [comment]
It's will give a warning says: not sequence... I' m on the Ubuntu 16.04
