### ISSUE TITLE
clang_format_custom.sublime-settings is completely ignored

### ISSUE THREAD

**Issue by amallia** [rosshemsley/SublimeClangFormat#44]
clang_format_custom.sublime-settings is completely ignored
```json
{
    "BasedOnStyle": "Google",
    "AlignConsecutiveAssignments": true,
    "ColumnLimit": 100,
    "UseTab": "Never",
    "TabWidth": 4,
}
```

**Comment by rosshemsley** [comment]
Did you (from command palette)  `Clang Format: Select Style` -> `Custom`?

**Comment by amallia** [comment]
No I want google style + some custom configuration. They are completely ignored!

**Comment by mikejmills** [comment]
Any resolution on this? I'm having the same issue.

**Comment by amallia** [comment]
Actually I solved this issue with:
> Did you (from command palette) Clang Format: Select Style -> Custom?

Another way is to put the following in `clang_format_custom.sublime-settings`
```
"style": "Custom"
```
