### ISSUE TITLE
Removing tabs in the whole file even when formatting few lines

### ISSUE THREAD

**Issue by reicrof** [rosshemsley/SublimeClangFormat#51]
I format only using spaces, but work with files that might contain both tabs and spaces. When working in some files that have both and try to format only a few lines, all the tabs in the file are converted to spaces. If the file is large, this creates a big diff and can be quite annoying to revert all the spaces to tabs. Could we have only the selected lines be changed instead of the whole file ?
Thanks :)

**Comment by reicrof** [comment]
The issue seems to come from the fact that we copy all of the formatted code, even when formatting a few lines. If the translate_tabs_to_spaces settings was set to true, sublime would change all the tabs to spaces, even when not part of the selection. I have create a small pull request if anyone is interested in the fix.

**Comment by sailormoon** [comment]
Thanks for the fix! It's been merged.
